### PR TITLE
Add support for array and nullable parameters in Action.Url

### LINKED ISSUE #116: Action.Url does not support array-valued parameters
I have an API method with the following signature:
```cs
IEnumerable<DataSeries> GetDashboardChart(string stateAbbr, [FromUri]string[] varNames)
```
The URL `GetDashboardChart?stateAbbr=&varNames=VAR1&varNames=VAR2` should result in a valid query to this method. However, there is no support for this in `Action.Url`. I have written a custom function to handle this case:

```cs
    public static string GetArrayQueryParams(IMethod method)
    {
        var arrayParameters = new List<string>();
        foreach (var parameter in method.Parameters)
        {
            if (parameter.Type.IsCollection && !parameter.HasAttribute("FromBody"))
            {
                arrayParameters.Add($"${{{parameter.Name}.map(item => `{parameter.Name}=${{item}}`).join('&')}}");
            }
        }
        return arrayParameters.Any() ? $"&{string.Join("&", arrayParameters)}" : string.Empty;
    }
```
Which results in the following TypeScript:
```ts
&${varNames.map(item => `varNames=${item}`).join('&')}
```
This works, but it would be better if this were built-in functionality.

### PR DESCRIPTION
**Pull request by tanguy-c**
Should fix #116 

I tried to create a local nuget to test with this fix, but I always have this warning :
You are using different version (0.5.9.0) of NTypewriter.Editor.Config than version used by runtime (0.5.8.0)
→ Any idea why?

### CODE REVIEW

**Comment by NeVeSpl** [comment]
> I tried to create a local nuget to test with this fix, but I always have this warning : You are using different version (0.5.9.0) of NTypewriter.Editor.Config than version used by runtime (0.5.8.0) → Any idea why?

The best way to test things is always through unit tests.  VS editor is compiled against specific versions of NTypewriter.Editor.Config nuget, and when csproj has a different version of this nuget installed, it kindly reminds to match versions.

**Comment by NeVeSpl** [comment]
I cannot accept this PR, your code editor has changed the formatting of the whitespaces, and the lines that did not change are shown as modified, which makes tracking of changes very hard ....

Also, I do think that adding `IType NonNullableType` to the public API is a good idea, the name is very confusing. That functionality should be rather placed into `ITypeExtensions.cs` as a new extension method with better name.

**Comment by tanguy-c** [comment]
> > I tried to create a local nuget to test with this fix, but I always have this warning : You are using different version (0.5.9.0) of NTypewriter.Editor.Config than version used by runtime (0.5.8.0) → Any idea why?
> 
> The best way to test things is always through unit tests. VS editor is compiled against specific versions of NTypewriter.Editor.Config nuget, and when csproj has a different version of this nuget installed, it kindly reminds to match versions.

Ok, just to be sure, the Visual Studio Extension is not open source (I can't build my own version) ?

I managed to create mine changing the DLLs in the vsix

**Comment by tanguy-c** [comment]
> I cannot accept this PR, your code editor has changed the formatting of the whitespaces, and the lines that did not change are shown as modified, which makes tracking of changes very hard ....
> 
> Also, I do think that adding `IType.NonNullableType` to the public API is a good idea, the name is very confusing. That functionality should be rather placed into `ITypeExtensions.cs` as a new extension method with better name.

Ok I see that too
I think I can make another PR today but I don't have much idea for the NonNullableType name
Do you prefer reusing the OriginalDefinition name or maybe Underlying

**Pull request closed without merging**
